# Generated by Django 4.2.1 on 2024-02-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='название тэга')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='filmnews',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='filmnews',
            index=models.Index(fields=['-time_create'], name='blog_filmne_time_cr_0ca540_idx'),
        ),
        migrations.AddField(
            model_name='filmnews',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag'),
        ),
    ]
